# config/config.yaml

active_provider: "gemini"

providers:
  gemini:
    api_key: "YOUR_GEMINI_API_KEY"
    model: "gemini-1.5-flash-latest"
  # ... 其他 provider 配置 ...

# 预设的邮件生成基础提示词
prompts:
  weekly_report: "总结本周项目的主要进展、挑战及下周计划。"
  marketing_campaign: "介绍我们的新产品特性，并提供一个限时优惠码。"

# 新增：結構化指令，用於組合和精細化控制 AI 生成
structured_instructions:
  tone_formal: "请使用非常正式和专业的商务书面语。"
  tone_casual: "请使用轻松、友好、非正式的口吻，可以适当使用 emoji。"
  format_json_array: "严格以 JSON 数组格式返回结果，数组的每个元素都是一份邮件正文的字符串。不要添加任何额外的解释或文本。"
  add_call_to_action: "在邮件末尾，加入明确的号召性用语（Call to Action），鼓励用户点击链接或回复邮件。"

# 新增：分离的 SMTP 账户配置
smtp_accounts:
  gmail_personal:
    host: "smtp.gmail.com"
    port: 587
    username: "your-personal@gmail.com"
    password: "GMAIL_APP_PASSWORD_1"
    from_alias: "你的个人邮箱"
  gmail_work:
    host: "smtp.gmail.com"
    port: 587
    username: "your-work@gmail.com"
    password: "GMAIL_APP_PASSWORD_2"
    from_alias: "你的工作团队"
  office365_main:
    host: "smtp.office365.com"
    port: 587
    username: "main@your-domain.com"
    password: "OFFICE365_PASSWORD"
    from_alias: "公司主邮箱"

# 新增：邮件发送策略
sending_strategies:
  default: # 默认策略，只使用一个账号
    policy: "round-robin" # 对于单个账号，策略无影响
    accounts:
      - "gmail_personal"
  round_robin_gmail: # 轮流使用两个 Gmail 账号发送
    policy: "round-robin"
    accounts:
      - "gmail_personal"
      - "gmail_work"
  random_all: # 随机从所有配置的账号中选择一个发送
    policy: "random"
    accounts:
      - "gmail_personal"
      - "gmail_work"
      - "office365_main"

# 邮件模板配置
templates:
  default: "templates/default_template.html"
  formal: "templates/formal_template.html"
  casual: "templates/casual_template.html"