# config/config.yaml

# 激活的 AI 提供商: "gemini", "doubao", "deepseek"
active_provider: "gemini"

# 各個 AI 提供商的配置
providers:
  gemini:
    api_key: "YOUR_GEMINI_API_KEY"
    model: "gemini-1.5-flash-latest"
  doubao:
    api_key: "YOUR_DOUBAO_API_KEY"
    secret_key: "YOUR_DOUBAO_SECRET_KEY"
  deepseek:
    api_key: "YOUR_DEEPSEEK_API_KEY"
    model: "deepseek-chat"

# 预设的邮件生成提示词
prompts:
  weekly_report: "以简洁、专业的口吻，总结本周项目的主要进展、遇到的挑战以及下周的详细计划。"
  marketing_campaign: "撰写一封吸引人的营销邮件，介绍我们的新产品特性，并提供一个限时优惠码。"
  team_update: "向团队成员同步一个重要的决定，解释其背后的原因，并鼓励大家提出问题。"

# SMTP 邮件服务器配置 (支持多邮箱分组)
smtp_groups:
  default: # 默认发件箱
    host: "smtp.gmail.com"
    port: 587
    username: "your-default-email@gmail.com"
    password: "YOUR_GMAIL_APP_PASSWORD"
    from_alias: "默认团队名"
  marketing: # 市场活动专用
    host: "smtp.office365.com"
    port: 587
    username: "marketing@your-domain.com"
    password: "YOUR_OFFICE365_PASSWORD"
    from_alias: "市场部"

# 邮件模板配置
templates:
  default: "templates/default_template.html"
  formal: "templates/formal_template.html"
  casual: "templates/casual_template.html"