# 选择要使用的 AI 提供商: "gemini", "doubao", "deepseek"
active_provider: "gemini"

# 各个 AI 提供商的配置
providers:
  gemini:
    api_key: "YOUR_GEMINI_API_KEY"
    # 可以根据需要添加其他模型名称，如 "gemini-1.5-pro-latest"
    model: "gemini-1.5-flash-latest" 
  
  doubao:
    # 豆包模型的 API Key 和 Secret Key 通常来自火山引擎或飞书开放平台
    api_key: "YOUR_DOUBAO_API_KEY"
    secret_key: "YOUR_DOUBAO_SECRET_KEY" 
    # API endpoint 可能需要在此处指定
    # base_url: "https://ark.cn-beijing.volces.com/api/v3/"

  deepseek:
    api_key: "YOUR_DEEPSEEK_API_KEY"
    # DeepSeek 的 API endpoint
    # base_url: "https://api.deepseek.com/v1"
    model: "deepseek-chat"

# SMTP 邮件服务器配置
smtp:
  host: "smtp.gmail.com"
  port: 587
  username: "your-email@gmail.com"
  # 强烈建议使用 App Password (应用专用密码)
  password: "YOUR_GMAIL_APP_PASSWORD" 
  # 发件人显示名称
  from_alias: "你的名字或团队"