# configs/email.yaml
# 负责所有 SMTP 发件账户的配置
# 注意：密码字段推荐使用应用专用密码（App Password），而不是您的主登录密码。

smtp_accounts:
  gmail_example:
    host: "smtp.gmail.com"
    port: 587
    username: "your-email@gmail.com"
    password: "YOUR_GMAIL_APP_PASSWORD" # 在此填入 Gmail 应用专用密码
    from_alias: "你的名字或团队" # 邮件中显示的发件人名称
  office365_example:
    host: "smtp.office365.com"
    port: 587
    username: "your-email@your-domain.com"
    password: "YOUR_OFFICE365_PASSWORD" # 在此填入 Office 365 账户密码
    from_alias: "你的公司"
